title: 种草の搞兔の陈大师
email: 569929309@qq.com
description: Wechat：hunterhug
about: > # this means to ignore newlines until "baseurl:"
  从没有见到如此厚颜无耻之人！
roll: >
  从没有见到如此厚颜の无耻之人！卡萨拉撒，卡姿兰便便变
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hunterhug.github.io" # the base hostname & protocol for your site
weibo_url: hunterhug
weibo_username: 太阳萌飞了のFollow WO 啦
github_username:  hunterhug
gems:
  - jekyll-coffeescript
  - jekyll-paginate
paginate: 8
paginate_path: "page:num"
# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: [README.md]
permalink: /:categories/:title.html
