title: Sun's Blog | 萌飞の家
email: gdccmcm14@live.com
description: Wechat：hunterhug
about: > # this means to ignore newlines until "baseurl:"
  我是一个略挫的学艺者，很傻很天真...
roll: >
  什么都不想说 2017.7...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hunterhug.github.io" # the base hostname & protocol for your site
weibo_url: hunterhug
weibo_username: 太阳萌飞了のFollow WO 啦
github_username:  hunterhug
gems:
  - jekyll-coffeescript
  - jekyll-paginate
paginate: nil
paginate_path: "page:num"
# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: [README.md]
permalink: /:categories/:title.html
