# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 一只尼玛 | ONESUN
email: gdccmcm14@live.com
description: > # this means to ignore newlines until "baseurl:"
  我是一个喜欢学知识的人，只是因为学了计算机，发现很多东西要学。<br />
  我用了一个星期，也可以说是五天，做出了至今为止第一个完整的博客。<br />
  我会很多计算机语言，C,C++,Python,PHP,JAVA,HTML,CSS,JS,MATLAB。<br />
  可是并没有卵用，并没有改变人类，呵呵。<br />
  我之前学了一学期数学，我知道数学家，计算机科学家和哲学家<br />
  从无到有创造东西真的很奇妙<br />
  比如不知从哪里学会了写网站，然后莫名奇妙的<br />
  晚上会突然做梦梦到学到很厉害的技术<br />
  可是却很害怕，因为摸不到<br />
  代码这种东西说来不复杂<br />
  只是顺从人的逻辑，提取数据再插入数据<br />
  自从得了精神病精神好多了<br />
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hunterhug.github.io/" # the base hostname & protocol for your site
twitter_username: hunterhug
twitterb_username: 一只尼玛_mark
github_username:  hunterhug
gems: [jekyll-paginate]
highlighter: true
paginate: 3
paginate_path: "page:num"
# Build settings
markdown: kramdown
