title: 一只尼玛
email: gdccmcm14@live.com
description: Wechat：hunterhug
about: > # this means to ignore newlines until "baseurl:"
  搬砖の陈大师One Nima（Sun）恢复原来的封号，面对太阳（嫌弃脸。。。
roll: >
  从没有见到如此厚颜の无耻之人！卡萨拉撒，卡姿兰便便变，biu~ 努力工作中...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hunterhug.github.io" # the base hostname & protocol for your site
weibo_url: hunterhug
weibo_username: 太阳萌飞了のFollow WO 啦
github_username:  hunterhug
gems:
  - jekyll-coffeescript
  - jekyll-paginate
paginate: nil
paginate_path: "page:num"
# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: [README.md]
permalink: /:categories/:title.html
