title: 一只尼玛
email: gdccmcm14@live.com
description: 伟大的程序员,只是一个技术博客,人生苦短，php不是最好的语言，我才是．
about: > # this means to ignore newlines until "baseurl:"
  我是一个喜欢学知识的人，只是因为学了计算机，发现很多东西要学。
  我会很多计算机语言，Go,Python,JAVA,C,C++,PHP,HTML,CSS,JS,MATLAB。
  可是并没有卵用，并没有改变人类，呵呵。
  大学时期学了一学期数学，我知道数学家，计算机科学家和哲学家
  从无到有创造东西真的很奇妙
  比如不知从哪里学会了写网站，然后莫名奇妙的
  晚上会突然做梦梦到学到很厉害的技术
  可是却很害怕，因为摸不到
  代码这种东西说来不复杂
  只是顺从人的逻辑，提取数据再插入数据
  自从得了精神病精神好多了
  现在苦逼程序员一个．
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hunterhug.github.io" # the base hostname & protocol for your site
weibo_url: hunterhug
weibo_username: 一只尼玛_mark
github_username:  hunterhug
duoshuo: hunterhug
gems:
  - jekyll-coffeescript
  - jekyll-paginate
paginate: 8
paginate_path: "page:num"
# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: [README.md]
permalink: /:categories/:title.html