title: 搬砖的陈大师|征途大海
email: 569929309@qq.com
description: 公众号：lenggirlcom
about: > # this means to ignore newlines until "baseurl:"
  一个搬砖的，不足挂齿
  但这里有爬虫，网站还有吐槽的故事
  云计算，中间件，和我半关系没有
  主要精通Go/Java/Python/Js以及各种工具的拼写。
  
  目前围绕Docker/kubernetes工作。
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hunterhug.github.io" # the base hostname & protocol for your site
weibo_url: hunterhug
weibo_username: 一只尼玛
github_username:  hunterhug
duoshuo: hunterhug
gems:
  - jekyll-coffeescript
  - jekyll-paginate
paginate: 8
paginate_path: "page:num"
# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: [README.md]
permalink: /:categories/:title.html
